# ---------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ---------------------------------------------------------------------------
# Name.......: apache-install.yml
# Author.....: Martin Berger (mbg) martin.berger@trivadis.com
# Editor.....: Martin Berger
# Date.......: 2021.03.14
# Revision...: 
# Purpose....: Apache Installation Playbook, uses sudo
# Notes......: --
# Reference..: --
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ---------------------------------------------------------------------------

---
- hosts: all
  become: yes
  tasks:
  - name: Install httpd Packages by YUM
    yum:
      name: httpd
      state: latest
  - name: Start httpd Service
    service:
      name: httpd 
      state: started
  - name: Enable port 80 in Firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart Service firewalld
    service: 
      name: firewalld 
      state: restarted

# --- EOF -------------------------------------------------------------------